import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseServer } from '@/lib/supabase-server'
import { jwtVerify } from 'jose'

const JWT_SECRET = process.env.JWT_SECRET || 'sar-admin-secret-key-2024'

async function verifyAdminAuth(request: NextRequest) {
  const token = request.cookies.get('admin-session')?.value
  if (!token) return null

  try {
    const secret = new TextEncoder().encode(JWT_SECRET)
    await jwtVerify(token, secret)
    return true
  } catch {
    return null
  }
}

/**
 * GET /api/admin/devops/tasks
 * Récupère la liste des tâches DevOps avec filtres
 */
export async function GET(request: NextRequest) {
  const isAuth = await verifyAdminAuth(request)
  if (!isAuth) {
    return NextResponse.json({ error: 'Non autorisé' }, { status: 401 })
  }

  try {
    const supabase = getSupabaseServer()
    const { searchParams } = new URL(request.url)

    // Filtres
    const status = searchParams.get('status')
    const department = searchParams.get('department')
    const priority = searchParams.get('priority')
    const assigned_to = searchParams.get('assigned_to')
    const layer = searchParams.get('layer')
    const search = searchParams.get('search')
    const limit = parseInt(searchParams.get('limit') || '100')
    const offset = parseInt(searchParams.get('offset') || '0')

    let query = supabase
      .from('devops_tasks')
      .select('*', { count: 'exact' })
      .order('last_activity_at', { ascending: false })
      .range(offset, offset + limit - 1)

    // Appliquer filtres
    if (status && status !== 'all') {
      query = query.eq('status', status)
    }

    if (department && department !== 'all') {
      query = query.eq('department', department)
    }

    if (priority && priority !== 'all') {
      query = query.eq('priority', priority)
    }

    if (layer && layer !== 'all') {
      query = query.eq('infrastructure_layer', layer)
    }

    if (assigned_to) {
      if (assigned_to === 'unassigned') {
        query = query.is('assigned_to', null)
      } else if (assigned_to !== 'all') {
        query = query.eq('assigned_to', assigned_to)
      }
    }

    // Full-text search
    if (search && search.trim()) {
      // Simple search on title and description
      query = query.or(`title.ilike.%${search}%,description.ilike.%${search}%,task_number.ilike.%${search}%`)
    }

    const { data: tasks, error, count } = await query

    if (error) {
      console.error('Erreur fetch tasks:', error)
      return NextResponse.json({ error: 'Erreur serveur', details: error.message }, { status: 500 })
    }

    return NextResponse.json({
      tasks: tasks || [],
      total: count || 0,
      limit,
      offset
    })

  } catch (error: any) {
    console.error('Erreur API GET /devops/tasks:', error)
    return NextResponse.json({
      error: 'Erreur serveur',
      details: error.message,
      stack: error.stack
    }, { status: 500 })
  }
}

/**
 * POST /api/admin/devops/tasks
 * Créer une nouvelle tâche DevOps
 */
export async function POST(request: NextRequest) {
  const isAuth = await verifyAdminAuth(request)
  if (!isAuth) {
    return NextResponse.json({ error: 'Non autorisé' }, { status: 401 })
  }

  try {
    const supabase = getSupabaseServer()
    const body = await request.json()

    // Validation des champs requis
    if (!body.title || !body.task_type || !body.department) {
      return NextResponse.json(
        { error: 'Champs requis manquants: title, task_type, department' },
        { status: 400 }
      )
    }

    const { data: task, error } = await supabase
      .from('devops_tasks')
      .insert({
        task_number: '', // Will be auto-generated by trigger
        title: body.title,
        description: body.description || null,
        task_type: body.task_type,
        department: body.department,
        infrastructure_layer: body.infrastructure_layer || null,
        priority: body.priority || 'medium',
        status: body.status || 'todo',
        assigned_to: body.assigned_to || null,
        assigned_at: body.assigned_to ? new Date().toISOString() : null,
        due_date: body.due_date || null,
        tags: body.tags || [],
        related_service: body.related_service || null,
        metadata: body.metadata || {},
        created_by: body.created_by || 'Frederic'
      })
      .select()
      .single()

    if (error) {
      console.error('Erreur création task:', error)
      return NextResponse.json({ error: 'Erreur création', details: error.message }, { status: 500 })
    }

    return NextResponse.json({ task }, { status: 201 })

  } catch (error) {
    console.error('Erreur API POST /devops/tasks:', error)
    return NextResponse.json({ error: 'Erreur serveur' }, { status: 500 })
  }
}
